run:
  timeout: 5m
  tests: true
  go: '1.23'

output:
  formats:
    - format: colored-line-number
  print-linter-name: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofumpt
    - gosec
    - revive
    - gocyclo
    - gocritic

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    enable-all: true
  
  gofumpt:
    extra-rules: true
  
  gocyclo:
    min-complexity: 15
  
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-checks:
      - unnamedResult
  
  revive:
    rules:
      - name: exported
      - name: error-return
      - name: error-naming
  
  gosec:
    excludes:
      - G404

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - gocyclo
