name: CD

on:
  push:
    branches: [main]

jobs:
  trigger-deploy:
    name: Trigger Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Trigger lauti-deployments
        run: |
          curl -X POST https://api.github.com/repos/LautaroBlasco23/lauti-deployments/dispatches \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -d '{"event_type":"deploy","client_payload":{"service":"life-tracker-backend"}}'
