// note_repository_test.go
//
// Subject:      internal/domain/note/repository.NoteRepository against real PostgreSQL.
// Scope:        CRUD operations — create, read with filters, update, hard-delete.
// Out of scope: Service-layer rules → note_service_test.go (integration)
//
//	HTTP contract       → note_controller_test.go
//
// Infrastructure: PostgreSQL (test database via .env.test).
// Data strategy:  TRUNCATE notes before each top-level test function.
// Parallel-safe:  No — single shared DB connection, no per-test namespace.
package repository

import (
	"fmt"
	"os"
	"testing"

	"life-tracker-backend/internal/config"
	"life-tracker-backend/internal/domain/note/dto"
	"life-tracker-backend/internal/domain/note/model"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

var (
	testDB *gorm.DB
	cfg    *config.Config
)

func TestMain(m *testing.M) {
	os.Setenv("ENVIRONMENT", "test")
	cfg = config.Load()
	os.Exit(m.Run())
}

func setupTestDatabase(t *testing.T) {
	t.Helper()
	if testDB != nil {
		return
	}

	dsn := fmt.Sprintf(
		"host=%s port=%s user=%s password=%s dbname=%s sslmode=%s",
		cfg.DBHost, cfg.DBPort, cfg.DBUser, cfg.DBPassword, cfg.DBName, cfg.DBSSLMode,
	)
	db, err := gorm.Open(postgres.Open(dsn), &gorm.Config{
		Logger: logger.Default.LogMode(logger.Silent),
	})
	require.NoError(t, err, "Failed to connect to PostgreSQL")

	sqlDB, err := db.DB()
	require.NoError(t, err)
	sqlDB.SetMaxOpenConns(1)

	require.NoError(t, db.AutoMigrate(&model.Note{}))
	testDB = db
}

func cleanDatabase(t *testing.T) {
	t.Helper()
	require.NoError(t, testDB.Exec("TRUNCATE TABLE notes RESTART IDENTITY CASCADE;").Error)
}

func getTestRepository(t *testing.T) *NoteRepository {
	t.Helper()
	setupTestDatabase(t)
	cleanDatabase(t)
	return NewNoteRepository(testDB)
}

// TestCreate verifies that Create persists a note and assigns a non-zero ID.
// Edge case: the passed-in note struct is mutated to include the generated primary key.
func TestCreate(t *testing.T) {
	repo := getTestRepository(t)

	t.Run("creates_note_and_sets_id", func(t *testing.T) {
		note := &model.Note{
			UserID:  100,
			Title:   "Test Note",
			Content: "Test content",
		}

		err := repo.Create(note)

		assert.NoError(t, err)
		assert.NotZero(t, note.ID, "ID should be auto-generated by database")
	})

	t.Run("creates_note_without_content", func(t *testing.T) {
		note := &model.Note{
			UserID: 101,
			Title:  "Title Only",
		}

		err := repo.Create(note)

		assert.NoError(t, err)
		assert.NotZero(t, note.ID)
	})
}

// TestFindByID verifies ownership enforcement: a note is only retrievable
// when both ID and userID match the stored record.
// Cross-ref: TestFindByID_wrong_user complements GetNote wrong_user in service tests.
func TestFindByID(t *testing.T) {
	repo := getTestRepository(t)
	userID := uint(200)

	note := &model.Note{UserID: userID, Title: "Private Note", Content: "Secret stuff"}
	require.NoError(t, testDB.Create(note).Error)

	t.Run("matching_userID_returns_note", func(t *testing.T) {
		found, err := repo.FindByID(note.ID, userID)

		assert.NoError(t, err)
		require.NotNil(t, found)
		assert.Equal(t, note.ID, found.ID)
		assert.Equal(t, note.Title, found.Title)
		assert.Equal(t, note.Content, found.Content)
		assert.Equal(t, userID, found.UserID)
	})

	t.Run("wrong_userID_returns_error", func(t *testing.T) {
		// The WHERE clause includes user_id, so querying with another user ID
		// produces gorm.ErrRecordNotFound.
		found, err := repo.FindByID(note.ID, 999)

		assert.Error(t, err)
		assert.Nil(t, found)
	})

	t.Run("non_existent_id_returns_error", func(t *testing.T) {
		found, err := repo.FindByID(9999, userID)

		assert.Error(t, err)
		assert.Nil(t, found)
	})
}

// TestFindByUserID verifies that listing returns only the requesting user's notes,
// ordered by updated_at DESC, and that the optional Query filter performs
// case-insensitive search across both title and content (PostgreSQL ILIKE).
func TestFindByUserID(t *testing.T) {
	repo := getTestRepository(t)
	userID := uint(201)

	// Seed notes for the test user
	seeds := []*model.Note{
		{UserID: userID, Title: "Meeting Notes", Content: "Discuss quarterly goals"},
		{UserID: userID, Title: "Book List", Content: "Clean Code, SICP"},
		{UserID: 999, Title: "Other User Note", Content: "Should be invisible"},
	}
	for _, n := range seeds {
		require.NoError(t, testDB.Create(n).Error)
	}

	t.Run("returns_user_notes_ordered_by_updated_at_desc", func(t *testing.T) {
		// Update the second note to make it more recent
		seeds[1].Content = "Clean Code, SICP, updated"
		require.NoError(t, testDB.Save(seeds[1]).Error)

		notes, err := repo.FindByUserID(userID, nil)

		assert.NoError(t, err)
		require.Len(t, notes, 2)
		// Should be ordered by updated_at DESC, so Book List (just updated) comes first
		assert.Equal(t, "Book List", notes[0].Title)
		assert.Equal(t, "Meeting Notes", notes[1].Title)
	})

	t.Run("no_filter_returns_all_user_notes", func(t *testing.T) {
		notes, err := repo.FindByUserID(userID, nil)

		assert.NoError(t, err)
		assert.Len(t, notes, 2)
	})

	t.Run("query_filter_matches_title_case_insensitively", func(t *testing.T) {
		filter := &dto.NoteFilter{Query: "meeting"}
		notes, err := repo.FindByUserID(userID, filter)

		assert.NoError(t, err)
		require.Len(t, notes, 1)
		assert.Equal(t, "Meeting Notes", notes[0].Title)
	})

	t.Run("query_filter_matches_content_with_ilike", func(t *testing.T) {
		filter := &dto.NoteFilter{Query: "clean code"}
		notes, err := repo.FindByUserID(userID, filter)

		assert.NoError(t, err)
		require.Len(t, notes, 1)
		assert.Equal(t, "Book List", notes[0].Title)
	})

	t.Run("query_filter_with_no_matches_returns_empty", func(t *testing.T) {
		filter := &dto.NoteFilter{Query: "xyznonexistent"}
		notes, err := repo.FindByUserID(userID, filter)

		assert.NoError(t, err)
		assert.Empty(t, notes)
	})

	t.Run("different_user_sees_no_notes", func(t *testing.T) {
		notes, err := repo.FindByUserID(888, nil)

		assert.NoError(t, err)
		assert.Empty(t, notes)
	})
}

// TestUpdate verifies that Update persists changes to an existing note.
// Edge case: Update modifies UpdatedAt timestamp automatically by GORM.
func TestUpdate(t *testing.T) {
	repo := getTestRepository(t)
	userID := uint(202)

	note := &model.Note{UserID: userID, Title: "Original Title", Content: "Original content"}
	require.NoError(t, testDB.Create(note).Error)
	originalUpdatedAt := note.UpdatedAt

	t.Run("updates_note_and_preserves_id", func(t *testing.T) {
		note.Title = "Updated Title"
		note.Content = "Updated content"

		err := repo.Update(note)

		assert.NoError(t, err)
		assert.Equal(t, uint(1), note.ID, "ID should remain unchanged")

		// Verify changes were persisted
		var updated model.Note
		require.NoError(t, testDB.First(&updated, note.ID).Error)
		assert.Equal(t, "Updated Title", updated.Title)
		assert.Equal(t, "Updated content", updated.Content)
		assert.True(t, updated.UpdatedAt.After(originalUpdatedAt), "UpdatedAt should be refreshed")
	})
}

// TestDelete verifies hard delete behavior: the row is removed from the database
// and subsequent reads return not-found. Wrong userID results in no rows affected
// but no error is returned (GORM Delete behavior with WHERE clause).
func TestDelete(t *testing.T) {
	repo := getTestRepository(t)
	userID := uint(203)

	t.Run("delete_removes_note_from_database", func(t *testing.T) {
		note := &model.Note{UserID: userID, Title: "To Delete", Content: "Goodbye"}
		require.NoError(t, testDB.Create(note).Error)

		err := repo.Delete(note.ID, userID)

		assert.NoError(t, err)

		// Verify note is actually deleted (hard delete)
		var count int64
		testDB.Model(&model.Note{}).Where("id = ?", note.ID).Count(&count)
		assert.Equal(t, int64(0), count, "Note should be permanently deleted")
	})

	t.Run("delete_with_wrong_userID_no_error_but_no_rows_affected", func(t *testing.T) {
		note := &model.Note{UserID: userID, Title: "Protected Note", Content: "Stay alive"}
		require.NoError(t, testDB.Create(note).Error)

		// Delete with wrong userID — no error returned, but no rows deleted
		err := repo.Delete(note.ID, 999)

		assert.NoError(t, err, "Delete should not error even with wrong userID")

		// Verify note still exists
		var stillThere model.Note
		findErr := testDB.First(&stillThere, note.ID).Error
		assert.NoError(t, findErr, "Note should still exist after failed delete")
		assert.Equal(t, "Protected Note", stillThere.Title)
	})

	t.Run("delete_non_existent_id_no_error", func(t *testing.T) {
		err := repo.Delete(9999, userID)

		assert.NoError(t, err, "Delete should not error for non-existent ID")
	})
}
